### ISSUE TITLE
ROUTE timeout is not working

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/framework4#12]
my ROUTE
total4.js
ROUTE("GET /test", handler, [1000], size || 5);
handler is Null

Request GET /test -> status 503 (About 10s)

total3.js
ROUTE("GET /test", handler, [1000], size || 5);
handler is Null

Request GET /test -> status 408 (1s)

total4.js is ROUTE Timeout is Not working...

**Comment by petersirka** [comment]
Hi @KangGeunSu. I have improved timeouts in Total.js 4. Timeouts are not precise because Total.js has five seconds interval (due to performance) that checks timeouts in all unclosed requests.

**Comment by KangGeunSu** [comment]
OK,
then
StatusCode is 503 correct?
The timeout seems to be 408.

Thank you

**Comment by petersirka** [comment]
Yes - it's correct. I have changed it from `408` to `503` because WebKit/Blink performs the request again if the response is `408`. So the web server could be overloaded with this behaviour.

**Comment by KangGeunSu** [comment]
OK!
Thank You!
