### ISSUE TITLE
MERGE incorrectly with versions auto

### ISSUE THREAD

**Issue by dispbd** [totaljs/framework4#15]
I have a concatenation of my scripts and styles in 2 files:
```javascript 
MERGE('/js/script.js', '/js/helpers.min.js', '/js/websocket-as-promised.min.js', '/js/jen.min.js');
MERGE('/css/style.css', '/css/main.css', '/css/tooltip.css');
```

Since these are static files, there is a need to enable versioning to resolve the cache issue in the release.
```
/js/script.js				: auto
/css/style.css				: auto
```

But the autoversion feature does not work with merged files in either debug or release mode.
The problem is the physical absence of the merged files - as soon as you create empty script files and autoversion styles, they start working.
https://i.vgy.me/bAbBeb.png

It would seem that you can leave it that way, but the second problem arises - during a livereload, the cache is formed incorrectly, which is why the client, when the page is auto-reloaded, swears for the absence of files.

**Comment by petersirka** [comment]
Thank you. I found a bug, can you test my fix?

- `$ npm install total4@beta`

**Comment by dispbd** [comment]
Yes, the bug has been fixed.
Thank you for efficiency! I close the ticket!

**Comment by petersirka** [comment]
Thank you, I'll release new version next week.
