### ISSUE TITLE
ROUTE flag Custom Content-Type

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/framework4#17]
Hello

I am trying to receive OneM2M data.

The Content-Type of OneM2M is application/vnd.onem2m-ntfy+xml;charset=UTF-8.

Which flag should I use to receive?

The only way to ignore content-type is **raw**?

**Comment by petersirka** [comment]
Hi @KangGeunSu,
I forgot to answer. Yes, you need to use `raw` route.

**Comment by KangGeunSu** [comment]
@petersirka 
Okay, thank you
