### ISSUE TITLE
Default translations doesn't work as expected

### ISSUE THREAD

**Issue by fgnm** [totaljs/framework4#23]
I've noticed another issue with total4 regarding translations. Some languages might have missing translations and I'd like to get the default one when this occurs. IIRC total3 worked like this, but now I get an empty string.

`default.resources`:
```
string-1           : String En 1
string-2           : String En 2
string-3           : String En 3
```

`it.resources`:
```
string-1           : String IT 1
```

Both in view engine and with `RESOURCE` function when I do `@(#string-3)` or `RESOURCE('it', 'string-3')` an empty string is returned but I'd like to have the default one, and so `String En 3`.

Not sure if this is a bug or an intended behaviour, if not is there a way to achieve this result?

Thanks

**Comment by petersirka** [comment]
The bug is same in Total.js 3. I have fixed this bug in Total.js 4, please try it `$ npm install total4@beta`.

**Comment by fgnm** [comment]
Thanks a lot!
