### ISSUE TITLE
Wrong status code when uploaded file is too large

### ISSUE THREAD

**Issue by fgnm** [totaljs/framework4#25]
Hi, I think this is another small bug in total4, I've this route rule which limit file upload to 1MB:
```JavaScript
ROUTE('+POST /admin/news/uploadImage   *News --> @uploadImage', ['upload', 120000], 1024); //Limit 1MB
```
When try to upload large files it correctly fails, but with a status code inconsistency between HTTP code and Json error description.

![image](https://user-images.githubusercontent.com/5543339/130218050-491a270d-bfb3-4be8-8e4f-cc02f3657fe0.png)

As you can see from this screenshot, HTTP status code is set to `400` while the error code is `431: Request Header Fields Too Large`. I think that HTTP status code should be set to `431` too. (I've noticed this bug because I'm used to check HTTP status code to show errors in front end).

Thanks!

**Comment by petersirka** [comment]
@fgnm I have fixed it. Today I'll publish a new beta version and I'll release it next week.

**Comment by petersirka** [comment]
I have released a new beta version: `$ npm install total4@beta`, you can test it.

**Comment by fgnm** [comment]
Thanks, works as expected now
