### ISSUE TITLE
Request to update "default_root"

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/framework4#26]
I made an example using **totaljs(git)/example/authorization**.
[example.zip](https://github.com/totaljs/framework4/files/7042724/example.zip)

# Common fixes

## ./views/homepage.html
* `<script src="https://cdn.componentator.com/spa.min@17.js"></script>`
-> `<script src="/js/spa.min@17.js"></script>`

* `<link rel="stylesheet" href="//cdn.componentator.com/spa.min@17.css" />`
-> `<link rel="stylesheet" href="/css/spa.min@17.css" />`

* add
-> `<script src="/js/ui.js"></script>`
-> `<link rel="stylesheet" href="/css/ui.css" />`

## File add
./public/js/
-> spa.min@17.js
-> ui.js

./public/css/
-> spa.min@17.css
-> ui.css

# Compare two files

## example.zip/authorization
-> total4 original

## example.zip/authorization_rw
-> node_modules/total4/utils.js

* `const REG_URLEXT = /(https|http|wss|ws|file):\/\/|\/\/[a-z0-9]|[a-z]:|@\{|/i;` (Line 96)
-> `const REG_URLEXT = /(https|http|wss|ws|file):\/\/|\/\/[a-z0-9]|[a-z]:/i;`

* `return REG_URLEXT.test(text) ? text : ((text[0] === 'h' ? 'href' : 'src') + '="' + CONF.default_root + (text[pos] === '/' ? text.substring(pos + 1) : text));` (Line 2551)
-> `return REG_URLEXT.test(text) ? text : ((text[0] === 'h' ? 'href' : 'src') + '="' + CONF.default_root + (text[pos] === '/' ? text.substring(pos + 1) : text.substring(pos)));`

# config
```
name					: Total.js Auth example

default_root				: /total

// IMPORTANT SETTINGS:
cookie		(generate)	: 10
cookie_secret	(generate)  	: 10
```

# Issues
## example.zip/authorization
![image](https://user-images.githubusercontent.com/11586458/130707305-cf0d3f17-b286-44b3-b5d0-777221df098b.png)

-> Call `http://localhost:8000/css/spa.min@17.css`
-> No "default_root" when calling "js" or "css".

## example.zip/authorization_rw
![image](https://user-images.githubusercontent.com/11586458/130707466-df43d13e-d63a-4234-b681-46e0115a1a64.png)

-> Call `http://localhost:8000/total/css/spa.min@17.css`
-> There is a "default_root" when calling "js" or "css".

Please help me to use "default_root"
Thank you

**Comment by petersirka** [comment]
Thank you so much.
Please try it now: `$ npm install total4@beta`. I have improved the functionality.

**Comment by KangGeunSu** [comment]
I checked it over the weekend.

I mostly write **FLOW**.
I wanted it to be "default_root" in "FLOW"

As a result, now seems to be the case.

It seems appropriate to modify the flow in the current state.

I will try more FLOW and reopen in FLOW.

Thank you very much.

**Comment by KangGeunSu** [comment]
How are you planning to do this?
```
var str = '<image width="150" height="150" xlink:href="{0}img/theme{1}.png" />'.format(url, common.theme || 'white'));
```

**Comment by petersirka** [comment]
Yes, there was a bug with `xlink:href` - I forgot on this type of attribute.

- updated Total.js 4 beta version `npm install total4@beta`
- download again `flow.package` https://github.com/totaljs/emptyproject-flow
- set `default_root` e.g. to `/subflow/`
- run it
- then let me know

**Comment by KangGeunSu** [comment]
Has confirmed
![image](https://user-images.githubusercontent.com/11586458/131424704-61ea59f9-3eea-4778-a824-96dc5ccdcb8d.png)


you are the best!!

The background didn't work either, so I tried to edit it a bit, but you solved it all at once.

It's really great!

Thank you always
