### ISSUE TITLE
Is "slength" correct in this part?

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/framework4#29]
https://github.com/totaljs/framework4/blob/950439be6ff76e13f8f9ef6b128330db97577284/index.js#L4765

Currently the code for "npm" is "for (var i = 0; i < flag.slength; i++) {".
When will you update?

**Comment by petersirka** [comment]
@KangGeunSu yes, thank you. I have fixed it and I have released a new beta version `$ npm install total4@beta`. Sorry for troubles and thank your for this report.

**Comment by petersirka** [comment]
I have released a new stable version. Thank you!
