### ISSUE TITLE
I want to send Body to GET in ROUTE & REQUET.

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/framework4#31]
I want to send Body to GET in ROUTE & REQUET.

The test failed.

Is there any possible way?

**Comment by petersirka** [comment]
`body` isn't possible to send with `GET` method :-(

**Comment by KangGeunSu** [comment]
Thank you!

Have a nice day~ :)

**Comment by petersirka** [comment]
@KangGeunSu I forgot - maybe with the `REQUEST()` you can send `body` via `GET` method, but Total.js doesn't handle it.
