### ISSUE TITLE
An alternative to try/catch error handler

### ISSUE THREAD

**Issue by LandyCuadra** [totaljs/framework4#43]
Is the feature request related to a problem? Please describe.

I would like to stop using try/catch in schemas methods, so I would like to know if there is a way to create an error collector, that every error that happens in any method get handled by a single block of code

Describe the solution you'd like

`    
try {

      //Operation

    }catch(err){
      const {name, message} = err;
      $.invalid(name, message);
      console.error(`SCHM: ${schema.name} | $${workflow} | ${method} | ${err.stack}`);
    }

`

I want to declare the catch handler only one time because it will always do the same

Describe alternatives you've considered

Tried overwritting the DEF.onError function, but could not find a way to send the controller to it

Additional context

**Comment by petersirka** [comment]
We don't use try/catch in the schemas. For example - here is a source code of one of our schema:

![image](https://user-images.githubusercontent.com/2414252/149564773-e10acf35-d19e-4ee0-aeab-a08f572133d2.png)

- error handling is automatically provided by the schema

**Comment by LandyCuadra** [comment]
but it do not return anything to the user.

for example this code: 
![Screenshot_20220114_122907](https://user-images.githubusercontent.com/33645795/149566771-a157cf75-cc2a-49e0-b18d-8c6f726e4c5c.png)

will broke because variable is not defined, so it throws an error to the console, but it do not return a error to the user.
![Screenshot_20220114_122834](https://user-images.githubusercontent.com/33645795/149566893-a935c32f-d455-400d-84fc-244dd1ff7a9c.png)

like it would do with try/catch
![Screenshot_20220114_123257](https://user-images.githubusercontent.com/33645795/149567199-abc9c15f-0837-48ce-a16a-89be72a66249.png)

**Comment by LandyCuadra** [comment]
What I would like to do is to send a controller to the default error handler to do a $.invalid() after showing the error in console or if there is a global way to return a response  on error

**Comment by petersirka** [comment]
@LandyCuadra this is not possible, because ErrorBuilder can be created without controller - for example via `EXEC()` method.

**Comment by molda** [comment]
@LandyCuadra the example with the undefined `variable` is actualy a bug and not something you should need try/catch for.
But if you want to avoid using try/catch you could try something like this:

```javascript
// global try/catch wrapper
function trycatch(handler) {
    return async function($, value) {
        let result;
        let error;
        try {
            result = await handler($, value);
        } catch(e) {
            error = e;
        }

        if (!error)
            $.success(result);
        else
            $.invalid(); // or any other logic
    };
};

schema.setQuery(trycatch(function($, value) {
    // do not use $.success or $.invalid here
    // just return data 
    return { anything: 'here' };
}));
```

**Comment by petersirka** [comment]
I'm closing issue.
