### ISSUE TITLE
[BUG] PROXY BUG

### ISSUE THREAD

**Issue by geunsukang** [totaljs/framework4#49]
Describe the bug
Missing port when using proxy.

To Reproduce
PROXY('/users/', 'http://localhost:**8001**/', false);

Expected behaviour
RESP : connect ECONNREFUSED localhost:**80**

Screenshots

![image](https://user-images.githubusercontent.com/20165271/209915053-d9ec35c7-7401-48c5-b805-24f8e1bc5690.png)

Must gather (please complete the following information):
 - total4@0.0.63
 - total4@0.0.71
 - node.js v14.21.1
 - Ubuntu 22.04

Additional context
Missing port when using proxy.
https://github.com/totaljs/framework4/blob/58f5d8f1a7d377d7954cdb6e835e803080c7689c/index.js#L8999

So, the request is made on the default port 80.

**Comment by petersirka** [comment]
Hi @geunsukang,
Sorry for the big delay. It's fixed. You can try it:

```
npm install total4@beta
```

New release will be next week. Thank you!

**Comment by geunsukang** [comment]
Thank you!
Happy new year!
